org: kauelima21

service: auth-service

provider:
  name: aws
  runtime: python3.12
  architecture: arm64
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'prod'}
  logRetentionInDays: 3
  environment: ${file(../../infra/env.yml)}
  httpApi: ${file(../../infra/http_api/config.yml)}
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: requirements.txt
    dockerizePip: true
    dockerPlatform: linux/arm64
    slim: true
    layer: true

package:
  individually: true
  patterns:
    - '!**'

functions:
  - ${file(functions.yml)}

resources:
  - ${file(../../infra/cognito/mailguru_user_pool.yml)}
  - ${file(../../infra/cognito/mailguru_user_pool_client.yml)}
