Resources:
  MailGuruUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MailGuruUserPoolClient
      UserPoolId: !Ref MailGuruUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AccessTokenValidity: 3
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        RefreshToken: days
